//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAFER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial
    {
        public int IdHistorial { get; set; }
        public string IdColegio { get; set; }
        public int IdAlumno { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public string CodigoPagoFacil { get; set; }
        public string Concepto { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
